version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    restart: always
    env_file:
      - .env
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_conf/alert-rules.yml:/etc/prometheus/alert-rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9091:9090"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - test-monitoring

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: always
    env_file:
      - .env
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./granfana_conf/granfana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./granfana_conf/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - test-monitoring

  alertmanager:
    image: prom/alertmanager:v0.28.0-rc.0
    container_name: alertmanager
    restart: always
    env_file:
      - .env
    volumes:
      - ./alertmanager_conf/alert-manager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - test-monitoring

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    restart: always
    env_file:
      - .env
    ports:
      - "9100:9100"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - test-monitoring

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: blackbox-exporter
    restart: always
    env_file:
      - .env
    volumes:
      - ./blackbox_conf/blackbox.yml:/etc/blackbox_exporter/config.yml
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    ports:
      - "9115:9115"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9115/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - test-monitoring


  mongo-exporter:
    image: percona/mongodb_exporter:0.43.1
    container_name: mongo-exporter
    restart: always
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME_EXPORTER}:${MONGO_PASSWORD_EXPORTER}@mongo:27017/admin
      - '--mongodb.global-conn-pool'
      - '--collector.diagnosticdata'
      - '--discovering-mode'
    ports:
      - "9216:9216"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9216/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - test-monitoring

  mysql-exporter:
    image: prom/mysqld-exporter:v0.16.0
    container_name: mysql-exporter
    restart: always
    env_file:
      - .env
    environment:
      - DATA_SOURCE_NAME=${MYSQL_USERNAME_EXPORTER}:${MYSQL_PASSWORD_EXPORTER}@(mysql:3306)/
    ports:
      - "9104:9104"
    depends_on:
      - mysql
    command:
      - "--mysqld.username=${MYSQL_USERNAME_EXPORTER}:${MYSQL_PASSWORD_EXPORTER}"
      - "--mysqld.address=mysql:3306"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9104/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - test-monitoring

  mongo:
    image: mongo:7.0.16-jammy
    container_name: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: ["--auth"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo_conf/mongod.conf:/etc/mongo/mongod.conf:ro
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - test-monitoring

  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - test-monitoring


networks:
  test-monitoring:
    driver: bridge
