global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert-rules.yml


alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx, http_404]
    static_configs:
      - targets:
          - https://zzz.vn/data
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'mongo-exporter'
    static_configs:
      - targets: ['mongo-exporter:9216']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance